blueprint:
  name: Blueprint
  title: carletonblueprint.org
  url: https://carletonblueprint.org
  image_url: https://images.ctfassets.net/7m5nzpb6x3ap/3IkXVZ3Mxy8cQA7V5XdIVL/e23bac708bdf9a879aaa5d42fb88847d/square_bluebg.png
